apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generatedby: OpenShiftWebConsole
  creationTimestamp: null
  labels:
    app: incdemo
  name: incdemo
spec:
  output:
    to:
      kind: ImageStreamTag
      name: incdemo:latest
  resources: {}
  source:
    git:
      ref: master
      uri: https://github.com/binarybabel/sti-rails-incremental-demo.git
    type: Git
  strategy:
    sourceStrategy:
      env:
      - name: BUILD_LOGLEVEL
        value: "5"
      from:
        kind: ImageStreamTag
        name: ruby:2.2
        namespace: openshift
      incremental: true
    type: Source
  triggers:
  - generic:
      secret: b64bfe85ed4c04ad
    type: Generic
  - github:
      secret: 919f0d9b62aae4ca
    type: GitHub
  - imageChange: {}
    type: ImageChange
  - type: ConfigChange
status:
  lastVersion: 0
